//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiHan.Libs.Sms.ServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SiHan.Libs.Sms.ServiceReference.LinkWSSoap")]
    internal interface LinkWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.HelloWorldResponse> HelloWorldAsync(SiHan.Libs.Sms.ServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BatchSend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.BatchSendResponse> BatchSendAsync(SiHan.Libs.Sms.ServiceReference.BatchSendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReportFail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.GetReportFailResponse> GetReportFailAsync(SiHan.Libs.Sms.ServiceReference.GetReportFailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Reg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.RegResponse> RegAsync(SiHan.Libs.Sms.ServiceReference.RegRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdPwd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.UpdPwdResponse> UpdPwdAsync(SiHan.Libs.Sms.ServiceReference.UpdPwdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdReg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.UpdRegResponse> UpdRegAsync(SiHan.Libs.Sms.ServiceReference.UpdRegRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelSum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.SelSumResponse> SelSumAsync(SiHan.Libs.Sms.ServiceReference.SelSumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.GetBalanceResponse> GetBalanceAsync(SiHan.Libs.Sms.ServiceReference.GetBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.SendResponse> SendAsync(SiHan.Libs.Sms.ServiceReference.SendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.GetResponse> GetAsync(SiHan.Libs.Sms.ServiceReference.GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UnReg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.UnRegResponse> UnRegAsync(SiHan.Libs.Sms.ServiceReference.UnRegRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChargeUp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.ChargeUpResponse> ChargeUpAsync(SiHan.Libs.Sms.ServiceReference.ChargeUpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgentChangeAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.AgentChangeAccountResponse> AgentChangeAccountAsync(SiHan.Libs.Sms.ServiceReference.AgentChangeAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BalanceMMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.BalanceMMSResponse> BalanceMMSAsync(SiHan.Libs.Sms.ServiceReference.BalanceMMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.SendMMSResponse> SendMMSAsync(SiHan.Libs.Sms.ServiceReference.SendMMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BatchSendMMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.BatchSendMMSResponse> BatchSendMMSAsync(SiHan.Libs.Sms.ServiceReference.BatchSendMMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReportFailMMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.GetReportFailMMSResponse> GetReportFailMMSAsync(SiHan.Libs.Sms.ServiceReference.GetReportFailMMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.GetMMSResponse> GetMMSAsync(SiHan.Libs.Sms.ServiceReference.GetMMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChargeUpMMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.ChargeUpMMSResponse> ChargeUpMMSAsync(SiHan.Libs.Sms.ServiceReference.ChargeUpMMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgentMakeAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.AgentMakeAccountResponse> AgentMakeAccountAsync(SiHan.Libs.Sms.ServiceReference.AgentMakeAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReportSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.GetReportSMSResponse> GetReportSMSAsync(SiHan.Libs.Sms.ServiceReference.GetReportSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReportMMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.GetReportMMSResponse> GetReportMMSAsync(SiHan.Libs.Sms.ServiceReference.GetReportMMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.Send2Response> Send2Async(SiHan.Libs.Sms.ServiceReference.Send2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMMS2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.SendMMS2Response> SendMMS2Async(SiHan.Libs.Sms.ServiceReference.SendMMS2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BatchSend2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.BatchSend2Response> BatchSend2Async(SiHan.Libs.Sms.ServiceReference.BatchSend2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IntlSend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.IntlSendResponse> IntlSendAsync(SiHan.Libs.Sms.ServiceReference.IntlSendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BatchSendMMS2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.BatchSendMMS2Response> BatchSendMMS2Async(SiHan.Libs.Sms.ServiceReference.BatchSendMMS2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VoiceNotify", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.VoiceNotifyResponse> VoiceNotifyAsync(SiHan.Libs.Sms.ServiceReference.VoiceNotifyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotSend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.NotSendResponse> NotSendAsync(SiHan.Libs.Sms.ServiceReference.NotSendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BatchContentSms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.BatchContentSmsResponse> BatchContentSmsAsync(SiHan.Libs.Sms.ServiceReference.BatchContentSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LinkSend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.LinkSendResponse> LinkSendAsync(SiHan.Libs.Sms.ServiceReference.LinkSendRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorld", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class HelloWorldRequest
    {
        
        public HelloWorldRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorldResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class HelloWorldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponse()
        {
        }
        
        public HelloWorldResponse(string HelloWorldResult)
        {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchSend", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class BatchSendRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Mobile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Content;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Cell;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string SendTime;
        
        public BatchSendRequest()
        {
        }
        
        public BatchSendRequest(string CorpID, string Pwd, string Mobile, string Content, string Cell, string SendTime)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.Mobile = Mobile;
            this.Content = Content;
            this.Cell = Cell;
            this.SendTime = SendTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchSendResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class BatchSendResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int BatchSendResult;
        
        public BatchSendResponse()
        {
        }
        
        public BatchSendResponse(int BatchSendResult)
        {
            this.BatchSendResult = BatchSendResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReportFail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetReportFailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string cell;
        
        public GetReportFailRequest()
        {
        }
        
        public GetReportFailRequest(string CorpID, string Pwd, string cell)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.cell = cell;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReportFailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetReportFailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetReportFailResult;
        
        public GetReportFailResponse()
        {
        }
        
        public GetReportFailResponse(string GetReportFailResult)
        {
            this.GetReportFailResult = GetReportFailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Reg", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class RegRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string CorpName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string LinkMan;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Tel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string Mobile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string Email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string Memo;
        
        public RegRequest()
        {
        }
        
        public RegRequest(string CorpID, string Pwd, string CorpName, string LinkMan, string Tel, string Mobile, string Email, string Memo)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.CorpName = CorpName;
            this.LinkMan = LinkMan;
            this.Tel = Tel;
            this.Mobile = Mobile;
            this.Email = Email;
            this.Memo = Memo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class RegResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int RegResult;
        
        public RegResponse()
        {
        }
        
        public RegResponse(int RegResult)
        {
            this.RegResult = RegResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdPwd", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class UpdPwdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string NewPwd;
        
        public UpdPwdRequest()
        {
        }
        
        public UpdPwdRequest(string CorpID, string Pwd, string NewPwd)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.NewPwd = NewPwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdPwdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class UpdPwdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int UpdPwdResult;
        
        public UpdPwdResponse()
        {
        }
        
        public UpdPwdResponse(int UpdPwdResult)
        {
            this.UpdPwdResult = UpdPwdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdReg", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class UpdRegRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string CorpName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string LinkMan;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Tel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string Mobile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string Email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string Memo;
        
        public UpdRegRequest()
        {
        }
        
        public UpdRegRequest(string CorpID, string Pwd, string CorpName, string LinkMan, string Tel, string Mobile, string Email, string Memo)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.CorpName = CorpName;
            this.LinkMan = LinkMan;
            this.Tel = Tel;
            this.Mobile = Mobile;
            this.Email = Email;
            this.Memo = Memo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdRegResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class UpdRegResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int UpdRegResult;
        
        public UpdRegResponse()
        {
        }
        
        public UpdRegResponse(int UpdRegResult)
        {
            this.UpdRegResult = UpdRegResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelSum", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class SelSumRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        public SelSumRequest()
        {
        }
        
        public SelSumRequest(string CorpID, string Pwd)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelSumResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class SelSumResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SelSumResult;
        
        public SelSumResponse()
        {
        }
        
        public SelSumResponse(int SelSumResult)
        {
            this.SelSumResult = SelSumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBalance", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetBalanceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        public GetBalanceRequest()
        {
        }
        
        public GetBalanceRequest(string CorpID, string Pwd)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBalanceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetBalanceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetBalanceResult;
        
        public GetBalanceResponse()
        {
        }
        
        public GetBalanceResponse(string GetBalanceResult)
        {
            this.GetBalanceResult = GetBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Send", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class SendRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Mobile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Content;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Cell;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string SendTime;
        
        public SendRequest()
        {
        }
        
        public SendRequest(string CorpID, string Pwd, string Mobile, string Content, string Cell, string SendTime)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.Mobile = Mobile;
            this.Content = Content;
            this.Cell = Cell;
            this.SendTime = SendTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class SendResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendResult;
        
        public SendResponse()
        {
        }
        
        public SendResponse(int SendResult)
        {
            this.SendResult = SendResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Get", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        public GetRequest()
        {
        }
        
        public GetRequest(string CorpID, string Pwd)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetResult;
        
        public GetResponse()
        {
        }
        
        public GetResponse(string GetResult)
        {
            this.GetResult = GetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UnReg", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class UnRegRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        public UnRegRequest()
        {
        }
        
        public UnRegRequest(string CorpID, string Pwd)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UnRegResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class UnRegResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int UnRegResult;
        
        public UnRegResponse()
        {
        }
        
        public UnRegResponse(int UnRegResult)
        {
            this.UnRegResult = UnRegResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChargeUp", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class ChargeUpRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string CardNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string CardPwd;
        
        public ChargeUpRequest()
        {
        }
        
        public ChargeUpRequest(string CorpID, string Pwd, string CardNo, string CardPwd)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.CardNo = CardNo;
            this.CardPwd = CardPwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChargeUpResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class ChargeUpResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ChargeUpResult;
        
        public ChargeUpResponse()
        {
        }
        
        public ChargeUpResponse(int ChargeUpResult)
        {
            this.ChargeUpResult = ChargeUpResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgentChangeAccount", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class AgentChangeAccountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string LoginName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string LoginPwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int SmsBalance;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int MmsBalance;
        
        public AgentChangeAccountRequest()
        {
        }
        
        public AgentChangeAccountRequest(string LoginName, string LoginPwd, string CorpID, int SmsBalance, int MmsBalance)
        {
            this.LoginName = LoginName;
            this.LoginPwd = LoginPwd;
            this.CorpID = CorpID;
            this.SmsBalance = SmsBalance;
            this.MmsBalance = MmsBalance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgentChangeAccountResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class AgentChangeAccountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AgentChangeAccountResult;
        
        public AgentChangeAccountResponse()
        {
        }
        
        public AgentChangeAccountResponse(string AgentChangeAccountResult)
        {
            this.AgentChangeAccountResult = AgentChangeAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BalanceMMS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class BalanceMMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        public BalanceMMSRequest()
        {
        }
        
        public BalanceMMSRequest(string CorpID, string Pwd)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BalanceMMSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class BalanceMMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string BalanceMMSResult;
        
        public BalanceMMSResponse()
        {
        }
        
        public BalanceMMSResponse(string BalanceMMSResult)
        {
            this.BalanceMMSResult = BalanceMMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMMS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class SendMMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Mobile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Base64Content;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Title;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string ExtCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string SendTime;
        
        public SendMMSRequest()
        {
        }
        
        public SendMMSRequest(string CorpID, string Pwd, string Mobile, string Base64Content, string Title, string ExtCode, string SendTime)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.Mobile = Mobile;
            this.Base64Content = Base64Content;
            this.Title = Title;
            this.ExtCode = ExtCode;
            this.SendTime = SendTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMMSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class SendMMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SendMMSResult;
        
        public SendMMSResponse()
        {
        }
        
        public SendMMSResponse(string SendMMSResult)
        {
            this.SendMMSResult = SendMMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchSendMMS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class BatchSendMMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Mobiles;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Base64Content;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Title;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string ExtCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string SendTime;
        
        public BatchSendMMSRequest()
        {
        }
        
        public BatchSendMMSRequest(string CorpID, string Pwd, string Mobiles, string Base64Content, string Title, string ExtCode, string SendTime)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.Mobiles = Mobiles;
            this.Base64Content = Base64Content;
            this.Title = Title;
            this.ExtCode = ExtCode;
            this.SendTime = SendTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchSendMMSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class BatchSendMMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string BatchSendMMSResult;
        
        public BatchSendMMSResponse()
        {
        }
        
        public BatchSendMMSResponse(string BatchSendMMSResult)
        {
            this.BatchSendMMSResult = BatchSendMMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReportFailMMS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetReportFailMMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string cell;
        
        public GetReportFailMMSRequest()
        {
        }
        
        public GetReportFailMMSRequest(string CorpID, string Pwd, string cell)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.cell = cell;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReportFailMMSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetReportFailMMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetReportFailMMSResult;
        
        public GetReportFailMMSResponse()
        {
        }
        
        public GetReportFailMMSResponse(string GetReportFailMMSResult)
        {
            this.GetReportFailMMSResult = GetReportFailMMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMMS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetMMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        public GetMMSRequest()
        {
        }
        
        public GetMMSRequest(string CorpID, string Pwd)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMMSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetMMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetMMSResult;
        
        public GetMMSResponse()
        {
        }
        
        public GetMMSResponse(string GetMMSResult)
        {
            this.GetMMSResult = GetMMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChargeUpMMS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class ChargeUpMMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string CardNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string CardPwd;
        
        public ChargeUpMMSRequest()
        {
        }
        
        public ChargeUpMMSRequest(string CorpID, string Pwd, string CardNo, string CardPwd)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.CardNo = CardNo;
            this.CardPwd = CardPwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChargeUpMMSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class ChargeUpMMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ChargeUpMMSResult;
        
        public ChargeUpMMSResponse()
        {
        }
        
        public ChargeUpMMSResponse(string ChargeUpMMSResult)
        {
            this.ChargeUpMMSResult = ChargeUpMMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgentMakeAccount", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class AgentMakeAccountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string LoginName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string LoginPwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string CorpName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string LinkMan;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Tel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string Mobile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string Email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string Memo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string Pass;
        
        public AgentMakeAccountRequest()
        {
        }
        
        public AgentMakeAccountRequest(string LoginName, string LoginPwd, string CorpName, string LinkMan, string Tel, string Mobile, string Email, string Memo, string CorpID, string Pass)
        {
            this.LoginName = LoginName;
            this.LoginPwd = LoginPwd;
            this.CorpName = CorpName;
            this.LinkMan = LinkMan;
            this.Tel = Tel;
            this.Mobile = Mobile;
            this.Email = Email;
            this.Memo = Memo;
            this.CorpID = CorpID;
            this.Pass = Pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgentMakeAccountResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class AgentMakeAccountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AgentMakeAccountResult;
        
        public AgentMakeAccountResponse()
        {
        }
        
        public AgentMakeAccountResponse(string AgentMakeAccountResult)
        {
            this.AgentMakeAccountResult = AgentMakeAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReportSMS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetReportSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        public GetReportSMSRequest()
        {
        }
        
        public GetReportSMSRequest(string CorpID, string Pwd)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReportSMSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetReportSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetReportSMSResult;
        
        public GetReportSMSResponse()
        {
        }
        
        public GetReportSMSResponse(string GetReportSMSResult)
        {
            this.GetReportSMSResult = GetReportSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReportMMS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetReportMMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        public GetReportMMSRequest()
        {
        }
        
        public GetReportMMSRequest(string CorpID, string Pwd)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReportMMSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetReportMMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetReportMMSResult;
        
        public GetReportMMSResponse()
        {
        }
        
        public GetReportMMSResponse(string GetReportMMSResult)
        {
            this.GetReportMMSResult = GetReportMMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Send2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class Send2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Mobile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Content;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Cell;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string SendTime;
        
        public Send2Request()
        {
        }
        
        public Send2Request(string CorpID, string Pwd, string Mobile, string Content, string Cell, string SendTime)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.Mobile = Mobile;
            this.Content = Content;
            this.Cell = Cell;
            this.SendTime = SendTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Send2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class Send2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Send2Result;
        
        public Send2Response()
        {
        }
        
        public Send2Response(string Send2Result)
        {
            this.Send2Result = Send2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMMS2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class SendMMS2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Mobile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Base64Content;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Title;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string ExtCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string SendTime;
        
        public SendMMS2Request()
        {
        }
        
        public SendMMS2Request(string CorpID, string Pwd, string Mobile, string Base64Content, string Title, string ExtCode, string SendTime)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.Mobile = Mobile;
            this.Base64Content = Base64Content;
            this.Title = Title;
            this.ExtCode = ExtCode;
            this.SendTime = SendTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMMS2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class SendMMS2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SendMMS2Result;
        
        public SendMMS2Response()
        {
        }
        
        public SendMMS2Response(string SendMMS2Result)
        {
            this.SendMMS2Result = SendMMS2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchSend2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class BatchSend2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Mobile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Content;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Cell;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string SendTime;
        
        public BatchSend2Request()
        {
        }
        
        public BatchSend2Request(string CorpID, string Pwd, string Mobile, string Content, string Cell, string SendTime)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.Mobile = Mobile;
            this.Content = Content;
            this.Cell = Cell;
            this.SendTime = SendTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchSend2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class BatchSend2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string BatchSend2Result;
        
        public BatchSend2Response()
        {
        }
        
        public BatchSend2Response(string BatchSend2Result)
        {
            this.BatchSend2Result = BatchSend2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IntlSend", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class IntlSendRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Mobile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Content;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Cell;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string SendTime;
        
        public IntlSendRequest()
        {
        }
        
        public IntlSendRequest(string CorpID, string Pwd, string Mobile, string Content, string Cell, string SendTime)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.Mobile = Mobile;
            this.Content = Content;
            this.Cell = Cell;
            this.SendTime = SendTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IntlSendResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class IntlSendResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string IntlSendResult;
        
        public IntlSendResponse()
        {
        }
        
        public IntlSendResponse(string IntlSendResult)
        {
            this.IntlSendResult = IntlSendResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchSendMMS2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class BatchSendMMS2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Mobiles;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Base64Content;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Title;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string ExtCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string SendTime;
        
        public BatchSendMMS2Request()
        {
        }
        
        public BatchSendMMS2Request(string CorpID, string Pwd, string Mobiles, string Base64Content, string Title, string ExtCode, string SendTime)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.Mobiles = Mobiles;
            this.Base64Content = Base64Content;
            this.Title = Title;
            this.ExtCode = ExtCode;
            this.SendTime = SendTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchSendMMS2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class BatchSendMMS2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string BatchSendMMS2Result;
        
        public BatchSendMMS2Response()
        {
        }
        
        public BatchSendMMS2Response(string BatchSendMMS2Result)
        {
            this.BatchSendMMS2Result = BatchSendMMS2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VoiceNotify", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class VoiceNotifyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Mobile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string verify_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string vtpl_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string show_num;
        
        public VoiceNotifyRequest()
        {
        }
        
        public VoiceNotifyRequest(string CorpID, string Pwd, string Mobile, string verify_code, string vtpl_id, string show_num)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.Mobile = Mobile;
            this.verify_code = verify_code;
            this.vtpl_id = vtpl_id;
            this.show_num = show_num;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VoiceNotifyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class VoiceNotifyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string VoiceNotifyResult;
        
        public VoiceNotifyResponse()
        {
        }
        
        public VoiceNotifyResponse(string VoiceNotifyResult)
        {
            this.VoiceNotifyResult = VoiceNotifyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NotSend", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class NotSendRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        public NotSendRequest()
        {
        }
        
        public NotSendRequest(string CorpID, string Pwd)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NotSendResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class NotSendResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string NotSendResult;
        
        public NotSendResponse()
        {
        }
        
        public NotSendResponse(string NotSendResult)
        {
            this.NotSendResult = NotSendResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchContentSms", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class BatchContentSmsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string JsonString;
        
        public BatchContentSmsRequest()
        {
        }
        
        public BatchContentSmsRequest(string CorpID, string Pwd, string JsonString)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.JsonString = JsonString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchContentSmsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class BatchContentSmsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string BatchContentSmsResult;
        
        public BatchContentSmsResponse()
        {
        }
        
        public BatchContentSmsResponse(string BatchContentSmsResult)
        {
            this.BatchContentSmsResult = BatchContentSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LinkSend", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class LinkSendRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CorpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Mobile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Content;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Cell;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string SendTime;
        
        public LinkSendRequest()
        {
        }
        
        public LinkSendRequest(string CorpID, string Pwd, string Mobile, string Content, string Cell, string SendTime)
        {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.Mobile = Mobile;
            this.Content = Content;
            this.Cell = Cell;
            this.SendTime = SendTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LinkSendResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class LinkSendResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string LinkSendResult;
        
        public LinkSendResponse()
        {
        }
        
        public LinkSendResponse(string LinkSendResult)
        {
            this.LinkSendResult = LinkSendResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal interface LinkWSSoapChannel : SiHan.Libs.Sms.ServiceReference.LinkWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal partial class LinkWSSoapClient : System.ServiceModel.ClientBase<SiHan.Libs.Sms.ServiceReference.LinkWSSoap>, SiHan.Libs.Sms.ServiceReference.LinkWSSoap
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LinkWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(LinkWSSoapClient.GetBindingForEndpoint(endpointConfiguration), LinkWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LinkWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LinkWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LinkWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LinkWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LinkWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.HelloWorldResponse> HelloWorldAsync(SiHan.Libs.Sms.ServiceReference.HelloWorldRequest request)
        {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.BatchSendResponse> BatchSendAsync(SiHan.Libs.Sms.ServiceReference.BatchSendRequest request)
        {
            return base.Channel.BatchSendAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.GetReportFailResponse> GetReportFailAsync(SiHan.Libs.Sms.ServiceReference.GetReportFailRequest request)
        {
            return base.Channel.GetReportFailAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.RegResponse> RegAsync(SiHan.Libs.Sms.ServiceReference.RegRequest request)
        {
            return base.Channel.RegAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.UpdPwdResponse> UpdPwdAsync(SiHan.Libs.Sms.ServiceReference.UpdPwdRequest request)
        {
            return base.Channel.UpdPwdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.UpdRegResponse> UpdRegAsync(SiHan.Libs.Sms.ServiceReference.UpdRegRequest request)
        {
            return base.Channel.UpdRegAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.SelSumResponse> SelSumAsync(SiHan.Libs.Sms.ServiceReference.SelSumRequest request)
        {
            return base.Channel.SelSumAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.GetBalanceResponse> GetBalanceAsync(SiHan.Libs.Sms.ServiceReference.GetBalanceRequest request)
        {
            return base.Channel.GetBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.SendResponse> SendAsync(SiHan.Libs.Sms.ServiceReference.SendRequest request)
        {
            return base.Channel.SendAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.GetResponse> GetAsync(SiHan.Libs.Sms.ServiceReference.GetRequest request)
        {
            return base.Channel.GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.UnRegResponse> UnRegAsync(SiHan.Libs.Sms.ServiceReference.UnRegRequest request)
        {
            return base.Channel.UnRegAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.ChargeUpResponse> ChargeUpAsync(SiHan.Libs.Sms.ServiceReference.ChargeUpRequest request)
        {
            return base.Channel.ChargeUpAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.AgentChangeAccountResponse> AgentChangeAccountAsync(SiHan.Libs.Sms.ServiceReference.AgentChangeAccountRequest request)
        {
            return base.Channel.AgentChangeAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.BalanceMMSResponse> BalanceMMSAsync(SiHan.Libs.Sms.ServiceReference.BalanceMMSRequest request)
        {
            return base.Channel.BalanceMMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.SendMMSResponse> SendMMSAsync(SiHan.Libs.Sms.ServiceReference.SendMMSRequest request)
        {
            return base.Channel.SendMMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.BatchSendMMSResponse> BatchSendMMSAsync(SiHan.Libs.Sms.ServiceReference.BatchSendMMSRequest request)
        {
            return base.Channel.BatchSendMMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.GetReportFailMMSResponse> GetReportFailMMSAsync(SiHan.Libs.Sms.ServiceReference.GetReportFailMMSRequest request)
        {
            return base.Channel.GetReportFailMMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.GetMMSResponse> GetMMSAsync(SiHan.Libs.Sms.ServiceReference.GetMMSRequest request)
        {
            return base.Channel.GetMMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.ChargeUpMMSResponse> ChargeUpMMSAsync(SiHan.Libs.Sms.ServiceReference.ChargeUpMMSRequest request)
        {
            return base.Channel.ChargeUpMMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.AgentMakeAccountResponse> AgentMakeAccountAsync(SiHan.Libs.Sms.ServiceReference.AgentMakeAccountRequest request)
        {
            return base.Channel.AgentMakeAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.GetReportSMSResponse> GetReportSMSAsync(SiHan.Libs.Sms.ServiceReference.GetReportSMSRequest request)
        {
            return base.Channel.GetReportSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.GetReportMMSResponse> GetReportMMSAsync(SiHan.Libs.Sms.ServiceReference.GetReportMMSRequest request)
        {
            return base.Channel.GetReportMMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.Send2Response> Send2Async(SiHan.Libs.Sms.ServiceReference.Send2Request request)
        {
            return base.Channel.Send2Async(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.SendMMS2Response> SendMMS2Async(SiHan.Libs.Sms.ServiceReference.SendMMS2Request request)
        {
            return base.Channel.SendMMS2Async(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.BatchSend2Response> BatchSend2Async(SiHan.Libs.Sms.ServiceReference.BatchSend2Request request)
        {
            return base.Channel.BatchSend2Async(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.IntlSendResponse> IntlSendAsync(SiHan.Libs.Sms.ServiceReference.IntlSendRequest request)
        {
            return base.Channel.IntlSendAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.BatchSendMMS2Response> BatchSendMMS2Async(SiHan.Libs.Sms.ServiceReference.BatchSendMMS2Request request)
        {
            return base.Channel.BatchSendMMS2Async(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.VoiceNotifyResponse> VoiceNotifyAsync(SiHan.Libs.Sms.ServiceReference.VoiceNotifyRequest request)
        {
            return base.Channel.VoiceNotifyAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.NotSendResponse> NotSendAsync(SiHan.Libs.Sms.ServiceReference.NotSendRequest request)
        {
            return base.Channel.NotSendAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.BatchContentSmsResponse> BatchContentSmsAsync(SiHan.Libs.Sms.ServiceReference.BatchContentSmsRequest request)
        {
            return base.Channel.BatchContentSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiHan.Libs.Sms.ServiceReference.LinkSendResponse> LinkSendAsync(SiHan.Libs.Sms.ServiceReference.LinkSendRequest request)
        {
            return base.Channel.LinkSendAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LinkWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.LinkWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LinkWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://mb345.com:999/ws/LinkWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.LinkWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://mb345.com:999/ws/LinkWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            LinkWSSoap,
            
            LinkWSSoap12,
        }
    }
}
